BolsaEmpleo/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from aspirante.views import index
from django.contrib.auth.views import login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^aspirante/', include('aspirante.urls', namespace="aspirante")),
    url(r'^empresa/', include('empresa.urls', namespace="empresa")),
    url(r'^administrador/', include('administrator.urls', namespace="administrador")),
    url(r'^usuario/', include('usuario.urls', namespace="usuario")),
    url(r'^login/', login, {'template_name':'login.html'}, name='login'),
    url(r'^evaluacion/', include('evaluacion.urls', namespace="evaluacion")),
    url(r'^$', admin.site.urls),
]

administrator/urls.py
from django.conf.urls import url
from . import views
from administrator.views import AreaTrabajoCreate, AreaTrabajoDelete, AreaTrabajoList, AreaTrabajoUpdate, \
    PuestoList, PuestoDelete, PuestoCreate, PuestoUpdate, DepartamentoList, MunicipioList

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^list_area_trabajo$', AreaTrabajoList.as_view(), name='area_trabajo_list'),
    url(r'^create_area_trabajo$', AreaTrabajoCreate.as_view(), name='area_trabajo_create'),
    url(r'^edit_area_trabajo/(?P<pk>\d+)/$', AreaTrabajoUpdate.as_view(), name='area_trabajo_editar'),
    url(r'^delete_area_trabajo/(?P<pk>\d+)/$', AreaTrabajoDelete.as_view(), name='area_trabajo_eliminar'),

    url(r'^list_puestos$', PuestoList.as_view(), name='puestos_list'),
    url(r'^create_puesto$', PuestoCreate.as_view(), name='puesto_create'),
    url(r'^edit_puesto/(?P<pk>\d+)/$', PuestoUpdate.as_view(), name='puesto_editar'),
    url(r'^delete_puesto/(?P<pk>\d+)/$', PuestoDelete.as_view(), name='puesto_eliminar'),

    url(r'^list_departamentos$', DepartamentoList, name='departamento_list'),
    url(r'^list_municipios$', MunicipioList, name='municipio_list'),

]

empresa/urls.py
from django.conf.urls import url
from . import views
from empresa.views import EmpresaList, EmpresaCreate, EmpresaUpdate, EmpresaDelete, \
    PuestoList, PuestoCreate, PuestoUpdate, PuestoDelete, \
    OfertaList, OfertaCreate, OfertaUpdate, OfertaDelete, senMail

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^list_empresas$', EmpresaList.as_view(), name='empresas_list'),
    url(r'^create_empresa$', EmpresaCreate.as_view(), name='empresa_create'),
    url(r'^edit_empresa/(?P<pk>\d+)/$', EmpresaUpdate.as_view(), name='empresa_editar'),
    url(r'^delete_empresa/(?P<pk>\d+)/$', EmpresaDelete.as_view(), name='empresa_eliminar'),

    url(r'^list_puestos$', PuestoList.as_view(), name='puestos_list'),
    url(r'^create_puesto$', PuestoCreate.as_view(), name='puesto_create'),
    url(r'^edit_puesto/(?P<pk>\d+)/$', PuestoUpdate.as_view(), name='puesto_editar'),
    url(r'^delete_puesto/(?P<pk>\d+)/$', PuestoDelete.as_view(), name='puesto_eliminar'),

    url(r'^list_ofertas$', OfertaList.as_view(), name='ofertas_list'),
    url(r'^create_oferta$', OfertaCreate.as_view(), name='oferta_create'),
    url(r'^edit_oferta/(?P<pk>\d+)/$', OfertaUpdate.as_view(), name='oferta_editar'),
    url(r'^delete_oferta/(?P<pk>\d+)/$', OfertaDelete.as_view(), name='oferta_eliminar'),

    url(r'^send_mail/', senMail, name='email_send'),
]

templates/administrador/catalogos/area_trabajo/area_trabajo_delete.html
{% extends 'base/base.html' %}
{% block title %}Empresa {% endblock %}

<div class="container">
{% block header %} <h2>Eliminar Empresa </h2> {% endblock %}
</div>
{% block content %}
    <form method="post">
    {% csrf_token %}
        <h3>Desea eliminar el area de trabajo {{ object.nombre }}</h3>
    <button class="btn btn-danger" type="submit">Si, eliminar</button>
    <a class="btn btn-default" href="{%  url 'empresa:empresas_list' %}">Cancelar</a>
    </form>
{% endblock %}

templates/administrador/catalogos/area_trabajo/area_trabajo_form.html
{% extends 'base/base.html' %}
{% block title %}Area de Trabajo {% endblock %}

<div class="container">
{% block header %}
<h2>Nueva Area de Trabajo</h2>
{% endblock %}
</div>
{% block content %}
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
    </form>
{% endblock %}

templates/administrador/catalogos/area_trabajo/area_trabajo_list.html
{% extends 'base/base.html' %}
{% block content %}
    <a class="btn btn-primary" href="{% url 'administrador:area_trabajo_create'%}">Nuevo</a>
    <br>
    <br>
    <table class="table table-bordered">
    <thead>
    <tr>
        <td>Nombre</td>
        <td>Descripcion</td>
        <td>Acciones</td>
    </tr>
    </thead>
    <tbody>
    {% if object_list %}
    {% for area in object_list %}
    <tr>
        <td>{{ area.nombre }}</td>
        <td>{{ area.descripcion }}</td>
        <td>
        <a class="btn btn-primary" href="{% url 'administrador:area_trabajo_editar' area.id %}">Editar</a>
        <a class="btn btn-danger" href="{% url 'administrador:area_trabajo_eliminar' area.id %}">Eliminar</a>
        </td>
    </tr>
    {% endfor %}
    {% else %}
    <h1>No hay registros</h1>
    {% endif %}
    </tbody>
    </table>
{% endblock %}